### PR TITLE
Added service fees to counselling services

### PR DESCRIPTION
**Pull request by ImaadJ10**
#### Summary:
- Adds isFree boolean data to counselling services

#### Changes:
- Added isFree data to counselling services model
- Updated API docs to include isFree data
- Updated counselling-servies.json and middleware to include isFree data
  
## Checklist

- [x] I performed a self-review of my code
- [x] I ran all the tests and they were successful

### CODE REVIEW

**Review by shivenshukla — APPROVED** [review]
LGTM!

**Comment by ImaadJ10** [comment]
[[🌟 Feature] Add service fees to counselling services](https://trello.com/c/eR0WCXTH/41-%F0%9F%8C%9F-feature-add-service-fees-to-counselling-services)

**Review by priyanshumahey — APPROVED** [review]
Looks good!

**Review by angusho1 — CHANGES_REQUESTED** [review]
@ImaadJ10 Can you add the `isFree` validator to `postRules` as well? Otherwise, LGTM

**Comment by ImaadJ10** [comment]
> @ImaadJ10 Can you add the `isFree` validator to `postRules` as well? Otherwise, LGTM

Added it!

**Review by jocelynbachmann — APPROVED** [review]

**Pull request merged**
