### PR TITLE
FE#25 Create Specialties Component

### PR DESCRIPTION
**Pull request by mayubi7**
#### Summary:
Adding a specialties component that displays a service's areas of specialty as chips.

#### Changes:
- Adds Specialties.tsx in the components folder
- Adds the specialties component to TestService.tsx

#### How to test this PR:
1. Go to the services page
2. Select a service
3. The service's specialties should be visible

## Screenshots:
Screen Shot 2023-03-19 at 9 14 47 PM

Screen Shot 2023-03-19 at 9 14 24 PM

## Checklist

- [x] I performed a self-review of my code

### CODE REVIEW

**Comment by mayubi7** [comment]
@angusho1 this line had eslint errors: `let id = serviceId.replace(/\W+/g, '-').replace(/\-$/, '').toLowerCase();`
I tried fixing it but now it's not fetching properly. Will probably look into it later, but if you get to it before me, can you maybe see why it's complaining?

**Comment by angusho1** [comment]
> @angusho1 this line had eslint errors: `let id = serviceId.replace(/\W+/g, '-').replace(/\-$/, '').toLowerCase();` I tried fixing it but now it's not fetching properly. Will probably look into it later, but if you get to it before me, can you maybe see why it's complaining?

@mayubi7 Jocelyn made a change in the React app to use environment variables in a `.env` file. This is so we can specify whether to use localhost or the deployed backend server URI when making requests. If you take a look in the `client` folder, there should be a `env.sample` file that you can copy into the `.env` file. Sorry for not mentioning this change earlier!

Speaking of that line of code, I created a [separate PR](https://trello.com/c/7B4bPQWz/26-use-secondaryid-in-full-service-page-route) to change the full page service routes to use the service's ID instead of the service name. That'll remove the need to parse this ID manually.

**Review by angusho1 — APPROVED** [review]
This looks great!

Just a couple of comments:
- We have a few components that are fetching the same data separately, so this logic should be refactored. Ideally, the full page component fetches the service data and passes it down to its children.
- The serviceId being passed to the component should already be properly formatted (but I know it currently isn't, so we need to change that).

We should address these in separate PRs though, so you can go ahead and merge this for now. Thanks!

**Comment by mayubi7** [comment]
That sounds good. I'll merge this and get started on those tickets :)

**Comment by mayubi7** [comment]
[Create Specialties Component](https://trello.com/c/voBkVhXK/25-create-specialties-component)

**Pull request merged**
