### PR TITLE
[BE#43] Modify GET response

### PR DESCRIPTION
**Pull request by shivenshukla**
# [BE#43](https://trello.com/c/Wz6KEOSl/43-%E2%9A%99%EF%B8%8F-task-define-response-objects-for-public-endpoints)

#### Summary:
- Modifes the response for GET endpoints

#### Changes:
- Removes _id field from GET response
- Removes __v field from GET response
- Returns school document in GET response

#### How to test this PR:
- Run automated tests
- Send Postman requests to GET /counselling-services or /schools
  
## Checklist

- [x] I performed a self-review of my code
- [x] I ran all the tests and they were successful

### CODE REVIEW

**Comment by shivenshukla** [comment]
[[⚙️ Task] Modify response for GET endpoints](https://trello.com/c/Wz6KEOSl/43-%E2%9A%99%EF%B8%8F-task-modify-response-for-get-endpoints)

**Review by angusho1 — CHANGES_REQUESTED** [review]
@shivenshukla It looks like the `GET /counselling-services/:id` single service endpoint is broken, as I'm getting `{ "message": "Cannot find service" }` for every service ID that I pass in. I realize we don't have tests for the single service endpoint.. Would you mind adding a couple so we can verify this endpoint works as expected?

Also, I noticed that sending the `GET /counselling-services` request (without any filters applied) isn't sending back all the services in the DB for some reason. In my local DB there are 12 services (the ones in `counselling-services.json`, but only 4 of those services are returned here.

Here are the returned services:

```
[
  {
    "serviceName": "My SSP",
    "school": {
      "uid": "sfu",
      "name": "Simon Fraser University",
      "abbreviation": "SFU",
      "mentalHealthCoverage": "80% of costs, up to $500 per policy year"
    },
    "organization": "Morneau Shepell (LifeWorks)",
    "serviceType": [
      "Counselling"
    ],
    "urgency": "Immediate",
    "targetClients": [
      "SFU students",
      "FIC students"
    ],
    "isAllDay": true,
    "website": "https://www.sfu.ca/students/health/get-support/my-ssp.html",
    "keywordSearch": [
      "Loneliness",
      "Stress and anxiety",
      "Identity",
      "Relationship conflicts or challenges",
      "Managing work/life balance",
      "Chronic health concerns",
      "Performance anxiety",
      "Homesickness",
      "Cultural adjustment",
      "Coping mechanisms",
      "Helping a friend in crisis"
    ],
    "specialty": [
      "Stress",
      "Anxiety",
      "Homesickness",
      "Cultural Adjustment"
    ],
    "delivery": [
      "Online",
      "Phone",
      "App"
    ],
    "description": "My SSP (My Student Support Program) is an app dedicated to supporting SFU/FIC students through its 24/7 crisis line, short-term counselling appointments and relevant resources on a range of mental health topics.",
    "secondaryID": "my-ssp"
  },
  {
    "serviceName": "ISC Wellness Program",
    "school": {
      "uid": "sfu",
      "name": "Simon Fraser University",
      "abbreviation": "SFU",
      "mentalHealthCoverage": "80% of costs, up to $500 per policy year"
    },
    "organization": "Indigenous Student Centre (ISC)",
    "serviceType": [
      "Wellness"
    ],
    "urgency": "Same Month",
    "targetClients": [
      "Indigenous SFU students"
    ],
    "isAllDay": false,
    "website": "https://www.sfu.ca/students/indigenous/isc-wellness.html",
    "keywordSearch": [],
    "specialty": [
      "Mental wellness",
      "Physical wellness",
      "Social wellness"
    ],
    "delivery": [
      "Online"
    ],
    "description": "The Wellness Program is a virtual community open to currently enrolled Indigenous students. Wherever you are, you can participate in a Run/Walk training program, learn about and share resources, engage with topics of mental, physical, and social wellness, and win prizes!",
    "secondaryID": "isc-wellness-program"
  },
  {
    "serviceName": "SFU Indigenous Counsellors",
    "school": {
      "uid": "sfu",
      "name": "Simon Fraser University",
      "abbreviation": "SFU",
      "mentalHealthCoverage": "80% of costs, up to $500 per policy year"
    },
    "organization": "SFU Health & Counselling Services (HCS)",
    "serviceType": [
      "Counselling"
    ],
    "urgency": "Same Month",
    "targetClients": [
      "SFU students"
    ],
    "isAllDay": false,
    "website": "https://www.sfu.ca/students/health/resources/identity/Indigenous-Students.html",
    "keywordSearch": [],
    "specialty": [
      "Stress",
      "Anxiety",
      "Depression",
      "Grief",
      "Trauma"
    ],
    "delivery": [
      "In Person"
    ],
    "description": "Counselling for Indigenous students is available with Tanu Gamble or Jennifer Reandy. To book an appointment, email isc_well@sfu.ca or learn more about counselling for Indigenous students here.",
    "secondaryID": "sfu-indigenous-counsellors"
  },
  {
    "serviceName": "Access Case Managers",
    "school": {
      "uid": "sfu",
      "name": "Simon Fraser University",
      "abbreviation": "SFU",
      "mentalHealthCoverage": "80% of costs, up to $500 per policy year"
    },
    "organization": "SFU Health & Counselling Services (HCS)",
    "serviceType": [
      "Counselling",
      "Wellness"
    ],
    "urgency": "Same Month",
    "targetClients": [
      "SFU students"
    ],
    "isAllDay": false,
    "website": "https://www.sfu.ca/students/health/get-support/hcs-service-navigators.html",
    "keywordSearch": [
      "Emotional support",
      "Distress surrounding international conflicts"
    ],
    "specialty": [
      "Stress",
      "Anxiety",
      "Depression",
      "Distress surrounding international conflicts"
    ],
    "delivery": [
      "Online",
      "Phone",
      "In Person"
    ],
    "description": "HCS (Health & Counselling Services) Drop-in Advising is here so you can speak with an Access Case Manager one-on-one and talk about how Health & Counselling can support you best - whether it's through regular counselling, groups, workshops or referrals.",
    "secondaryID": "access-case-managers"
  }
]
```

Otherwise, the response bodies themselves look good. Let me know if you're not able to reproduce these issues or if you have any questions. Thanks for all your work on this :)

**Comment by shivenshukla** [comment]
> @shivenshukla It looks like the `GET /counselling-services/:id` single service endpoint is broken, as I'm getting `{ "message": "Cannot find service" }` for every service ID that I pass in. I realize we don't have tests for the single service endpoint.. Would you mind adding a couple so we can verify this endpoint works as expected?
> 
> Also, I noticed that sending the `GET /counselling-services` request (without any filters applied) isn't sending back all the services in the DB for some reason. In my local DB there are 12 services (the ones in `counselling-services.json`, but only 4 of those services are returned here.

@angusho1 

Actually, we do have tests for GET /counselling-services/:id. I added another one.

The aggregation pipeline performs a lookup for the school document. This operation creates a dependency between the counselling service and school document. If the school does not exist in the database, then the lookup fails resulting the "Cannot find service" error.

I will investigate if there is a way to remove this dependency so that if the school does not exist, the response will return null for the school field instead.

**Comment by angusho1** [comment]
> I will investigate if there is a way to remove this dependency so that if the school does not exist, the response will return null for the school field instead.

That would be perfect, thanks!

By the way, I'm not sure if you're aware, but there is a way to link the counselling service and school schemas directly by defining the school field in the CounsellingService as a reference to the School schema. But, this would be a totally different approach as we'd be storing the MongoDB _id for the school instead of the human-friendly school ID. I think there would be quite a few changes, so don't bother switching to this if you can find a solution with the current approach. I'm just mentioning this in case you find this approach to have more advantages than the other one.

https://mongoosejs.com/docs/schematypes.html#objectids

https://stackoverflow.com/questions/18001478/referencing-another-schema-in-mongoose

**Comment by shivenshukla** [comment]
Thank you @angusho1 reviewing and testing this PR thoroughly.

I fixed the issue. If the school document does not exist, then the school field will appear in the response. I hope this is OK?

> By the way, I'm not sure if you're aware, but there is a way to link the counselling service and school schemas directly by defining the school field in the CounsellingService as a reference to the School schema. But, this would be a totally different approach as we'd be storing the MongoDB _id for the school instead of the human-friendly school ID. I think there would be quite a few changes, so don't bother switching to this if you can find a solution with the current approach. I'm just mentioning this in case you find this approach to have more advantages than the other one.

I was not aware. I thought aggregation was only to way to link documents in responses. I am guessing this is what you were referring to when you mentioned it during the team meeting a while back.

One problem with aggregation is that it is less performant than using find. I don't expect performance being as issue for our application because we don't have many documents in our database. But, if we do find that GET requests are slow in the future, we should revisit this and consider using the approach you mentioned.

**Comment by angusho1** [comment]
> I fixed the issue. If the school document does not exist, then the school field will not appear in the response. I hope this is OK?

This sounds good to me, thanks. I'll make sure that our schools collections are populated with enough schools.

> I was not aware. I thought aggregation was only to way to link documents in responses. I am guessing this is what you were referring to when you mentioned it during the team meeting a while back.
> 
> One problem with aggregation is that it is less performant than using find. I don't expect performance being as issue for our application because we don't have many documents in our database. But, if we do find that GET requests are slow in the future, we should revisit this and consider using the approach you mentioned.

Yes, I had the ObjectId in mind when I mentioned document references during one of our meetings. Sorry, I probably should've mentioned it directly. But, I think your solution is fine as it stands, and like you said we're not concerned with performance right now. We can keep this in mind for the future if it does end up becoming a problem.

**Review by angusho1 — APPROVED** [review]
All looks good to me now. Thanks for all your work on this!

**Pull request merged**
