### PR TITLE
[BE#36] Modify filtering to include a search parameter

### PR DESCRIPTION
**Pull request by shivenshukla**
# [BE#36](https://trello.com/c/q6HVgaTJ/36-%F0%9F%8C%9F-feature-modify-filtering-to-include-a-search-parameter)

#### Summary:
- Adds text search to GET / counselling-services

#### Changes:
- Adds text index to the Counselling Service schema
- Adds search parameter to GET /counselling-services

#### How to test this PR:
- Use Postman to send GET requests to /counselling-services

### CODE REVIEW

**Comment by shivenshukla** [comment]
[[🌟 Feature] Modify filtering to include a search parameter](https://trello.com/c/q6HVgaTJ/36-%F0%9F%8C%9F-feature-modify-filtering-to-include-a-search-parameter)

**Review by angusho1 — CHANGES_REQUESTED** [review]
Search logic looks good, but it looks like the endpoint is broken if `searchString` isn't included as query parameter. I tried sending a request without params and got the following error message: 
```
{
"message": "\"$search\" had the wrong type. Expected string, found null"
}
```

Could you fix this? You can run the integration test to verify that there's 1 test failing. Thanks!

**Comment by shivenshukla** [comment]
Should be fixed now : )

**Review by angusho1 — APPROVED** [review]
Looks great!

**Pull request merged**
