### PR TITLE
[FE#13] Create filter bar component

### PR DESCRIPTION
**Pull request by angusho1**
#### Summary:
- Adds a filter bar component to the home page with 5 filters: Support Type, Delivery Method, Urgency, Specialty, and School

#### Changes:
- Adds reusable `FilterDropdown.tsx` component for a single filter category
- Adds `FilterBar.tsx` component that consists of 5 filters and a button to clear the filters
- Modifies the search bar and home page CSS so that it's structured the same as the wireframe
- Adds 2 extra data fetches in the home page to retrieve the list of schools and list of specialties
- Makes Urgency and School as single-select filters (radio buttons)
- Makes Support Type, Delivery Method, and Specialty as multi-select filters (check boxes)

#### How to test this PR:
- Visit the Netlify deploy preview link below (data might take a while to load the first time if the backend server is down and needs to restart. Could be a couple of minutes!)
- After data has loaded, all 5 filters should have a list of options (might need to refresh)
- Try different combos of filters, the services should reload as soon as you change an option
  - The filtering works as follows: It returns services that match the requirement of EVERY filter. If a filter is multi-select, then it returns services that match ANY of the selected options. This logic has already been tested on the backend, so we just need to make sure we are sending the correct query string.
  - You can verify it's working by using the browser debug tools and looking at the network requests sent. The request payload should show the query parameters that correspond to the filter (see screenshots for examples)
  - The "Any" option in a single-select filter doesn't include a query parameter in the request
- Clicking "Clear All Filters" should show all the data again 

## Screenshots:
Screenshot 2023-04-04 at 6 34 26 PM
Screenshot 2023-04-04 at 6 36 31 PM
  
## Checklist

- [x] I performed a self-review of my code
- [x] (Backend only) I ran all the tests using `npm test` and they were successful
- [x] (Backend only) I ran the linter using `npm run lint` and there were no errors

### CODE REVIEW

**Comment by angusho1** [comment]
[Create Filter Bar Component](https://trello.com/c/HRp2K3hf/13-create-filter-bar-component)

**Review by jocelynbachmann — APPROVED** [review]
Looks good! Idk if in the future we might want to put some kind of loading page since the backend takes so long to start up

**Comment by angusho1** [comment]
> Looks good! Idk if in the future we might want to put some kind of loading page since the backend takes so long to start up

Good idea, I'll create a ticket for that

**Comment by mayubi7** [comment]
It looks great! It's nice to see the home page coming together. Just a few comments:
1. For the checkboxes and radio buttons maybe they should be a different colour other than blue so they're more consistent with the theme?
2. We might want to have a message like "No services found" for the scenario where the filters provide no matching services.

**Review by mayubi7 — APPROVED** [review]

**Comment by angusho1** [comment]
> It looks great! It's nice to see the home page coming together. Just a few comments:
> 
> 1. For the checkboxes and radio buttons maybe they should be a different colour other than blue so they're more consistent with the theme?
> 2. We might want to have a message like "No services found" for the scenario where the filters provide no matching services.

@mayubi7 Thanks for the feedback! Great ideas, I'll make those changes in this PR since they're super minor.

Speaking of the theme, eventually we'll need to define the theme colours and fonts in MUI. I'll change the check box colour for now, but later on we'll need to refactor the colour definitions.

**Pull request merged**
