### PR TITLE
[BE#47] Clean up server files

### PR DESCRIPTION
**Pull request by angusho1**
#### Summary:
- Updated all API-related docs and files and fixed linting errors

#### Changes:
- Removed `route.rest` file
- Updated Postman collection with up-to-date data and endpoints
- Updated `documentation` folder API docs with latest response data
- Fixed linting errors
- Updated PR template to include lint check

#### How to test this PR:
- Please take a look through the changed API doc files to double check they are accurate
- Make sure the ESLint extension in VS Code is installed and working, and that you can run `npm run lint` without errors. To check that the extension is working, make changes in some files that will break linting rules, and the errors should appear in VS Code.
- Import the Postman collection, and all endpoints should be up to date
  
## Checklist

- [x] I performed a self-review of my code
- [x] I ran all the tests and they were successful

### CODE REVIEW

**Comment by angusho1** [comment]
[[⚙️ Task] Clean codebase - API methods, API doc files](https://trello.com/c/cqJ3xpeI/47-%E2%9A%99%EF%B8%8F-task-clean-codebase-api-methods-api-doc-files)

**Review by priyanshumahey — APPROVED** [review]
LGTM. Tested the changes and they were working fine on my end.

**Review by shivenshukla — APPROVED** [review]
LGTM!

Minor suggestion: We should decide if the uid of the school should be all uppercase or lowercase. In the Postman collection, the post request for counselling services uses "SFU" for the school but the post request for schools uses "sfu" as the uid.

**Comment by angusho1** [comment]
> LGTM!
> 
> Minor suggestion: We should decide if the uid of the school should be all uppercase or lowercase. In the Postman collection, the post request for counselling services uses "SFU" for the school but the post request for schools uses "sfu" as the uid.

Thanks for the suggestion. We should definitely keep the school uids lowercase to be consistent with our other IDs.

**Review by jocelynbachmann — APPROVED** [review]

**Review by ImaadJ10 — APPROVED** [review]

**Pull request merged**
