### PR TITLE
[BE#31] Validate POST and PATCH request

### PR DESCRIPTION
**Pull request by shivenshukla**
# [BE#31](https://trello.com/c/Sh887R8Q/31-%E2%9A%99%EF%B8%8F-task-parse-and-validate-request-inputs-for-post-and-patch-requests)

#### Summary:
Add validation to POST and PATCH requests.

#### Changes:
- Adds [express-validator](https://www.npmjs.com/package/express-validator).
- Adds middleware to validate requests.

#### How to test this PR:
- Manually run invalid requests using Postman OR run automated tests using `npm test`

### CODE REVIEW

**Comment by shivenshukla** [comment]
[[⚙️ Task] Parse and validate request inputs for POST and PATCH requests](https://trello.com/c/Sh887R8Q/31-%E2%9A%99%EF%B8%8F-task-parse-and-validate-request-inputs-for-post-and-patch-requests)

**Review by angusho1 — CHANGES_REQUESTED** [review]
Looks great, I like the use of the validator middleware, it's really clean. Thanks for writing all those tests too.

@shivenshukla One small thing - for the "invalid request" error message, could you indicate which field in the body is invalid? It would help a lot on the client side for debugging - it took me a while to figure out what was wrong with my request body when I was testing 😆 . If there's multiple invalid fields, I think just indicating the first invalid field is fine. Thanks!

**Comment by shivenshukla** [comment]
> Looks great, I like the use of the validator middleware, it's really clean. Thanks for writing all those tests too.
> 
> @shivenshukla One small thing - for the "invalid request" error message, could you indicate which field in the body is invalid? It would help a lot on the client side for debugging - it took me a while to figure out what was wrong with my request body when I was testing 😆 . If there's multiple invalid fields, I think just indicating the first invalid field is fine. Thanks!

The dependency actually returns an array of all invalid fields by default, but I suppressed it by returning the "invalid request" instead.

I will fix that. Thanks.

**Comment by shivenshukla** [comment]
@angusho1 - Fixed the error messages. They should be more detailed now.

**Comment by angusho1** [comment]
> @angusho1 - Fixed the error messages. They should be more detailed now.

That's great, it looks good now - much more helpful messages. Thanks for the changes

**Review by angusho1 — APPROVED** [review]

**Pull request merged**
