### PR TITLE
FE#28 Refactor data fetching

### PR DESCRIPTION
**Pull request by angusho1**
#### Summary:
- Refactors data fetching logic in the frontend so that components don't call `fetch` directly

#### Changes:
- Created new `api.ts` files for functions that fetch data from the server
- Refactored Home and Full Service Page to only call these functions at top-level components

#### How to test this PR:
- Visit the home page and full service pages. All the data should load as expected, and there should be no visible changes to the user
  
## Checklist

- [x] I performed a self-review of my code
- [x] I ran the linter using `npm run lint` and there were no errors

### CODE REVIEW

**Comment by angusho1** [comment]
[Refactor data fetching logic](https://trello.com/c/rGLZXIRI/28-refactor-data-fetching-logic)

**Review by jocelynbachmann — COMMENTED** [review]
The requests are hanging for me on the remote server and locally, there's this error in the console:
```
TypeError: Failed to fetch
    at getCounsellingServices (:3000/static/js/bundle.js:158:21)
    at :3000/static/js/bundle.js:1061:109
    at invokePassiveEffectCreate (:3000/static/js/bundle.js:56175:24)
    at HTMLUnknownElement.callCallback (:3000/static/js/bundle.js:36791:18)
    at Object.invokeGuardedCallbackDev (:3000/static/js/bundle.js:36840:20)
    at invokeGuardedCallback (:3000/static/js/bundle.js:36900:35)
    at flushPassiveEffectsImpl (:3000/static/js/bundle.js:56257:13)
    at unstable_runWithPriority (:3000/static/js/bundle.js:68259:16)
    at runWithPriority$1 (:3000/static/js/bundle.js:44197:14)
    at flushPassiveEffects (:3000/static/js/bundle.js:56134:18)
```

**Comment by angusho1** [comment]
> The requests are hanging for me on the remote server and locally, there's this error in the console:
> 
> ```
> TypeError: Failed to fetch
>     at getCounsellingServices (:3000/static/js/bundle.js:158:21)
>     at :3000/static/js/bundle.js:1061:109
>     at invokePassiveEffectCreate (:3000/static/js/bundle.js:56175:24)
>     at HTMLUnknownElement.callCallback (:3000/static/js/bundle.js:36791:18)
>     at Object.invokeGuardedCallbackDev (:3000/static/js/bundle.js:36840:20)
>     at invokeGuardedCallback (:3000/static/js/bundle.js:36900:35)
>     at flushPassiveEffectsImpl (:3000/static/js/bundle.js:56257:13)
>     at unstable_runWithPriority (:3000/static/js/bundle.js:68259:16)
>     at runWithPriority$1 (:3000/static/js/bundle.js:44197:14)
>     at flushPassiveEffects (:3000/static/js/bundle.js:56134:18)
> ```

@jocelynbachmann Hmm it's working for me locally.. Are you able to send the request to your server via Postman?

And for the remote server, there was an issue with the Render deployment a while back. I tried rebuilding it and the deployment was successful but I think it's still not running properly. I'll try to take a look and see what's wrong.

**Comment by angusho1** [comment]
Looks like Render's having a lot of issues, a lot of people are getting the same thing: https://community.render.com/search?q=502%20order%3Alatest. We probably can't rely on having our deploys available then..

**Review by mayubi7 — APPROVED** [review]
Looks great and works for me locally. Just want to add though the home page looks like this for me:
Screen Shot 2023-05-14 at 5 26 19 PM
Do we want to maybe have the cards use flex instead of having them fixed length? Or center the elements in the middle of the page so we don't have lots of whitespace?
That can definitely be addressed in a different ticket though.

**Comment by mayubi7** [comment]
Actually after more testing I see this error on my console:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Home
o`

**Comment by angusho1** [comment]
> Do we want to maybe have the cards use flex instead of having them fixed length? Or center the elements in the middle of the page so we don't have lots of whitespace? That can definitely be addressed in a different ticket though.

I agree, the layout of the cards needs a lot of improvement. We should definitely be using responsive styling and filling up the horizontal space as much as we can. I'll make sure to create another ticket to address this.

> Actually after more testing I see this error on my console: `Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function at Home`

Hmm.. I'm not able to reproduce this, could you give some more detail? Did the error show up on a simple page load, or after you interacted with some components?

**Review by jocelynbachmann — APPROVED** [review]
It's working locally for me now, not sure what was going on last time. I'm not getting the memory leak error @mayubi7 mentioned either

**Pull request merged**
