### PR TITLE
[BE#37] Improve Dependabot

### PR DESCRIPTION
**Pull request by shivenshukla**
# [BE#37](https://trello.com/c/gxcCLPua/37-%E2%9A%99%EF%B8%8F-task-set-up-github-dependabot)

#### Summary:
Improves Dependabot configuration.

#### Changes:
- Adds Dependabot to the client directory
- Adds a versioning strategy so that Dependabot modifies package.json
- Limits open pull requests to 1

#### How to test this PR:
- Can not test functionality until this PR is merged to main
  
## Checklist

- [x] I performed a self-review of my code
- [x] I ran all the tests and they were successful

### CODE REVIEW

**Comment by shivenshukla** [comment]
[[⚙️ Task] Set up GitHub Dependabot](https://trello.com/c/gxcCLPua/37-%E2%9A%99%EF%B8%8F-task-set-up-github-dependabot)

**Comment by angusho1** [comment]
@shivenshukla I believe the `package-lock.json` file in the root directory is there because of people accidentally running `npm install` in the root directory in the past. We can remove it altogether unless there's a good reason to manage shared dependencies across the client and server.

**Comment by shivenshukla** [comment]
> @shivenshukla I believe the `package-lock.json` file in the root directory is there because of people accidentally running `npm install` in the root directory in the past. We can remove it altogether unless there's a good reason to manage shared dependencies across the client and server.

Makes sense. I removed the lock file and added it .gitignore.

**Comment by angusho1** [comment]
> Makes sense. I removed the lock file and added it to .gitignore.

Great, thanks.

**Review by angusho1 — APPROVED** [review]

**Pull request merged**
